# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferenceDialog.ui'
#
# Created by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(642, 254)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.channelHeader = QtGui.QLabel(self.tab)
        self.channelHeader.setGeometry(QtCore.QRect(10, 20, 201, 16))
        self.channelHeader.setObjectName("channelHeader")
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(10, 50, 601, 110))
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.ch1Label = QtGui.QLabel(self.widget)
        self.ch1Label.setObjectName("ch1Label")
        self.gridLayout.addWidget(self.ch1Label, 0, 0, 1, 1)
        self.ch1LineEdit = QtGui.QLineEdit(self.widget)
        self.ch1LineEdit.setObjectName("ch1LineEdit")
        self.gridLayout.addWidget(self.ch1LineEdit, 0, 1, 1, 1)
        self.browseCh1Button = QtGui.QPushButton(self.widget)
        self.browseCh1Button.setObjectName("browseCh1Button")
        self.gridLayout.addWidget(self.browseCh1Button, 0, 2, 1, 1)
        self.ch2Label = QtGui.QLabel(self.widget)
        self.ch2Label.setObjectName("ch2Label")
        self.gridLayout.addWidget(self.ch2Label, 1, 0, 1, 1)
        self.ch2LineEdit = QtGui.QLineEdit(self.widget)
        self.ch2LineEdit.setObjectName("ch2LineEdit")
        self.gridLayout.addWidget(self.ch2LineEdit, 1, 1, 1, 1)
        self.browseCh2Button = QtGui.QPushButton(self.widget)
        self.browseCh2Button.setObjectName("browseCh2Button")
        self.gridLayout.addWidget(self.browseCh2Button, 1, 2, 1, 1)
        self.ch3Label = QtGui.QLabel(self.widget)
        self.ch3Label.setObjectName("ch3Label")
        self.gridLayout.addWidget(self.ch3Label, 2, 0, 1, 1)
        self.ch3LineEdit = QtGui.QLineEdit(self.widget)
        self.ch3LineEdit.setObjectName("ch3LineEdit")
        self.gridLayout.addWidget(self.ch3LineEdit, 2, 1, 1, 1)
        self.browseCh3Button = QtGui.QPushButton(self.widget)
        self.browseCh3Button.setObjectName("browseCh3Button")
        self.gridLayout.addWidget(self.browseCh3Button, 2, 2, 1, 1)
        self.ch4Label = QtGui.QLabel(self.widget)
        self.ch4Label.setObjectName("ch4Label")
        self.gridLayout.addWidget(self.ch4Label, 3, 0, 1, 1)
        self.ch4LineEdit = QtGui.QLineEdit(self.widget)
        self.ch4LineEdit.setObjectName("ch4LineEdit")
        self.gridLayout.addWidget(self.ch4LineEdit, 3, 1, 1, 1)
        self.browseCh4Button = QtGui.QPushButton(self.widget)
        self.browseCh4Button.setObjectName("browseCh4Button")
        self.gridLayout.addWidget(self.browseCh4Button, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.channelHeader.setText(QtGui.QApplication.translate("Dialog", "Configure Default Image Locations", None, QtGui.QApplication.UnicodeUTF8))
        self.ch1Label.setText(QtGui.QApplication.translate("Dialog", "Channel 1", None, QtGui.QApplication.UnicodeUTF8))
        self.browseCh1Button.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.ch2Label.setText(QtGui.QApplication.translate("Dialog", "Channel 2", None, QtGui.QApplication.UnicodeUTF8))
        self.browseCh2Button.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.ch3Label.setText(QtGui.QApplication.translate("Dialog", "Channel 3", None, QtGui.QApplication.UnicodeUTF8))
        self.browseCh3Button.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.ch4Label.setText(QtGui.QApplication.translate("Dialog", "Channel 4", None, QtGui.QApplication.UnicodeUTF8))
        self.browseCh4Button.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "PlaceHolder", None, QtGui.QApplication.UnicodeUTF8))

